csv to json
pycontw/mail_handler pull request #29
Opened 2021-06-27 09:27 UTC by oldman3483

Convert the member data from csv file to json file to use the mailhandler

2021-06-27 14:35 UTC, josix requested changes

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +def readcsv(fname:str) -> (list):
The parentheses in `(list)` is redundant. Using `list` is OK. Moreover, Using `List[str]` from typing module is better.
```suggestion
from typing import List
#...
def readcsv(file_name:str) -> List[str]:
```

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +def csv2json(uniquefname:str, commonfname:str) -> (dict):
Same as line 5. Let's do following update. 
```suggestion
from typing import Dict, List
#...
def csv2json(uniquefname:str, commonfname:str) -> Dict[str, List[str]]:
```

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +            item = item.encode('utf-8').decode('utf-8-sig').strip()
I'm not sure if this decoding is necessary. Why shall we do this?

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +    memdata = []
I'm not sure the meaning of `mem` is. Maybe we could use a meaningful one.

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +    list_uniquedata = []
The type prefix is redundant. It is probably breaks when the actual type of this variable change in the future. The better way to represent its type is using type hint like following
```suggestion
    unique_data: List[Dict[str, str]] = []
```

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +        out = out.replace("'", '"')
For the json conversion, we could use `json.dumps` instead of casting to string directly.
https://docs.python.org/3/library/json.html

2021-06-27 14:35 UTC, josix commented on csv2json/csv2json.py
> +            outjson.write(out)
Using `json.dump` is OK. Are there any concern for using it?

2021-06-27 15:36 UTC, Lee-W commented
You could follow the steps [here](https://pycontw.github.io/mail_handler/contributing/) to ensure you pass the checks

2021-06-27 15:46 UTC, Lee-W requested changes
Thanks for your contribution! 🙏 I just leave some comments. Hope it helps!

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +def readcsv(fname:str) -> (list):
I'd suggest using `read_csv` insetad of `readcsv`.  Also an additional space between `file_name` and `str` would be better (i.e., `file_name: str`)

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +            #print(memdata)
I'd suggest removing this line

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +def csv2json(uniquefname:str, commonfname:str) -> (dict):
I prefer using `csv_to_json`.

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    #print(list_uniquedata)
I'd suggest remove this line as well

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    #print(list_commondata)
I'd suggest remove this line as well

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    uniquefname = input() #'./memberdata.csv'
use `unque_file_name` would be more readable than `uniquefname`

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    uniquefname = input() #'./memberdata.csv'
what does the comment mean? is it the default value?

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +        out = (str(list_res))
the outer bracket seems to be redundant

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    commonfname = input() #'./commondata.csv'
same as the above line

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +
Please remove redundant empty lines.

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +import  json
Please remove redundant space

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    for i in range(len(memdata)-1):
How about using `enumerate`?

e.g.,

```python
for data_index, data in enumerate(memdata[:-1]):
    unique_data.append({data, mem_data[data_index+1]})
```

Note that the naming might need some fixing as I don't fully understand the meaning of these names

2021-06-27 15:46 UTC, Lee-W commented on csv2json/csv2json.py
> +    uniquefname = input() #'./memberdata.csv'
If `input()` is used, prompt message is suggested. e.g., `input("Please enter file name: ")`

2021-08-09 04:33 UTC, josix commented
Hello @oldman3483, is there any update?

2021-10-09 10:59 UTC, closed without merging