New feature: support of using HTML template
pycontw/mail_handler pull request #43
Opened 2022-04-18 07:39 UTC by andylee830914

## Types of changes

- **New feature** : support of using HTML template

## Description
1. HTML validation by lxml. 
2. Detection of HTML. If HTML format detected, file generated in *mails_to_send* will have `.html` extension.
Otherwise, plain text mail will have a `.txt` extension.
3. Support image attachment embedded.
4. Fix test cases to support .html and .txt filename extension.

## Checklist:
- [ ] Add test cases to all the changes you introduce (Not html data yet)
- [x] Run `inv style` locally to ensure all linter checks pass
- [x] Run `inv test` locally to ensure all test cases pass
- [x] Run `inv secure` locally to ensure no major vulnerability is introduced
- [x] Update the documentation if necessary

2022-04-19 07:14 UTC, tai271828 requested changes
1) Some nitpicking for your reference. I will leave it to your judgement to update the nitpicking or not.
2) CI failed for dependency. Would you mind fixing it?
3) Feel free to suggest someone to review next time so they will also get email notification. It is also great to give people heads-up on discord, which you have already done that, and I saw the discord thread and came here.

2022-04-19 07:14 UTC, tai271828 commented on mail_handler/render_mail.py
> +        if "<html>" in mail_content:
fwiw: I may use a html parser to validate the content.

2022-04-19 07:14 UTC, tai271828 commented on pyproject.toml
> +lxml = "^4.7.1"
CI does not pass for the dependency checking. Would you mind fixing the CI failure? Thanks!

2022-04-20 09:14 UTC, andylee830914 commented on mail_handler/render_mail.py
> +        if "<html>" in mail_content:
I discard lxml and use python built-in html parser to check the mail_content is HTML or not.

2022-04-20 09:14 UTC, andylee830914 commented on pyproject.toml
> +lxml = "^4.7.1"
I update all the outdated package versions. Now CI are all passed.

2022-04-22 22:46 UTC, tai271828 commented on pyproject.toml
> +click = "^8.1.2"
fwiw: I know click `^8.1.0` has some encoding known issue. We can keep this in mind if any encoding error happens to us.

2022-04-22 22:49 UTC, tai271828 commented on pyproject.toml
> +click = "^8.1.2"
Ah this is it! https://github.com/pycontw/mail_handler/runs/6091941742?check_suite_focus=true Hmmm but why did the same error not happen to this commit? Is it because `8.1.2` fixed the issue already?

2022-04-22 22:52 UTC, tai271828 approved these changes
I am not sure why click `8.1.2` does not raise CI failure. Maybe `8.1.2.` fixes the known encoding issue or I did not remember something correctly. However, we can fix click version if anything wrong with it later.

I think this pull request is good to good. Thank Andy for your contribution.

2022-04-22 22:52 UTC, merged

2022-04-23 06:34 UTC, andylee830914 commented on pyproject.toml
> +click = "^8.1.2"
I found this issue in repo of Black. Old version of Black is incompatible with click version after 8.1.0.
So I bump both click and black to the latest version. 

https://github.com/psf/black/issues/2964